"""Layer 3 substrate-specific xTB helpers (v3 coworker review).

Optional quantum refinements used by Module -1 and Module 2.
All functions are fallback-safe when RDKit/xTB are unavailable.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

try:
    from rdkit import Chem
    from rdkit.Chem import AllChem
except Exception:  # pragma: no cover - optional dependency
    Chem = None
    AllChem = None

try:
    from enzyme_software.calibration.layer1_empirical import (
        bde_record as l1_bde_record,
        bde_kj_mol as l1_bde_kj_mol,
    )
except Exception:  # pragma: no cover - optional dependency
    def l1_bde_record(bond_class: str) -> Dict[str, Any]:
        return {}

    def l1_bde_kj_mol(bond_class: str, default: float = 410.0) -> float:
        return float(default)


CALIBRATION_VERSION = "layer3_xtb.v3_coworker_review"
HARTREE_TO_KJ_MOL = 2625.5
H_ATOM_ENERGY_HARTREE = -0.3935
TOTAL_ENERGY_RE = re.compile(r"TOTAL ENERGY\s+(-?\d+\.\d+)")
BDE_SAFEGUARD_THRESHOLD_KJ_MOL = 30.0
N_CONFORMERS = 5
XTB_MAX_ATOMS = 80
VALID_RADICAL_HEAVY_ATOMS = {"C", "N", "O", "S"}

_CACHE_DIR = Path(__file__).resolve().parent / "cache" / "layer3_xtb"
_CACHE_DIR.mkdir(parents=True, exist_ok=True)


def is_layer3_xtb_enabled() -> bool:
    raw = str(os.environ.get("ENZYME_LAYER3_XTB", "")).strip().lower()
    return raw in {"1", "true", "yes", "on"}


def xtb_available(xtb_path: str = "xtb") -> bool:
    return shutil.which(xtb_path) is not None


class XTBCalculator:
    """Small xTB runner with opt/single-point helpers."""

    def __init__(
        self,
        xtb_path: str = "xtb",
        method: str = "gfn2",
        solvent: Optional[str] = "water",
        n_cores: int = 1,
        timeout_s: int = 300,
    ):
        self.xtb_path = xtb_path
        self.method = method
        self.solvent = solvent
        self.n_cores = max(1, int(n_cores))
        self.timeout_s = max(30, int(timeout_s))

    def _run(
        self,
        xyz_path: str,
        *,
        charge: int = 0,
        uhf: int = 0,
        optimize: bool = False,
        workdir: Optional[str] = None,
    ) -> Tuple[str, str, int]:
        cmd = [self.xtb_path, xyz_path, "--gfn", "2", "--chrg", str(charge), "--uhf", str(max(0, int(uhf)))]
        if self.solvent:
            cmd += ["--alpb", str(self.solvent)]
        if self.n_cores > 1:
            cmd += ["--parallel", str(self.n_cores)]
        if optimize:
            cmd.append("--opt")
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=workdir,
            timeout=self.timeout_s,
            check=False,
        )
        return proc.stdout or "", proc.stderr or "", int(proc.returncode)

    @staticmethod
    def _parse_energy_hartree(stdout: str, stderr: str) -> float:
        text = (stdout or "") + "\n" + (stderr or "")
        match = TOTAL_ENERGY_RE.search(text)
        if not match:
            raise ValueError("xTB TOTAL ENERGY not found")
        return float(match.group(1))

    def energy_from_xyz(
        self,
        xyz_text: str,
        *,
        charge: int = 0,
        uhf: int = 0,
        optimize: bool = False,
    ) -> float:
        with tempfile.TemporaryDirectory(prefix="xtb_l3_") as tmp:
            xyz_path = Path(tmp) / "mol.xyz"
            xyz_path.write_text(xyz_text, encoding="utf-8")
            stdout, stderr, rc = self._run(
                str(xyz_path),
                charge=charge,
                uhf=uhf,
                optimize=optimize,
                workdir=tmp,
            )
            if rc != 0:
                raise RuntimeError((stderr or stdout)[:500])
            return self._parse_energy_hartree(stdout, stderr)


def _mol_to_xyz_string(mol: Any, conf_id: int = -1, remove_atom_idx: Optional[int] = None) -> Optional[str]:
    if mol is None or mol.GetNumConformers() == 0:
        return None
    conf = mol.GetConformer(conf_id)
    atom_indices = [idx for idx in range(mol.GetNumAtoms()) if idx != remove_atom_idx]
    lines = [str(len(atom_indices)), "generated by layer3_xtb"]
    for idx in atom_indices:
        atom = mol.GetAtomWithIdx(idx)
        pos = conf.GetAtomPosition(idx)
        lines.append(f"{atom.GetSymbol():2s} {pos.x:14.8f} {pos.y:14.8f} {pos.z:14.8f}")
    return "\n".join(lines) + "\n"


def _build_radical_from_parent(
    mol_h: Any,
    *,
    heavy_idx: int,
    h_idx: int,
) -> Tuple[Optional[Any], Optional[int]]:
    """Build a parent-minus-H radical and set explicit radical electrons."""
    if Chem is None:
        return None, None
    try:
        radical = Chem.RWMol(Chem.Mol(mol_h))
        if radical.GetBondBetweenAtoms(int(heavy_idx), int(h_idx)) is None:
            return None, None
        radical.RemoveBond(int(heavy_idx), int(h_idx))
        radical.RemoveAtom(int(h_idx))
        new_heavy_idx = int(heavy_idx) if int(h_idx) > int(heavy_idx) else int(heavy_idx) - 1
        atom = radical.GetAtomWithIdx(int(new_heavy_idx))
        atom.SetNumRadicalElectrons(1)
        atom.SetNoImplicit(True)
        try:
            Chem.SanitizeMol(radical)
        except Exception:
            pass
        return radical.GetMol(), int(new_heavy_idx)
    except Exception:
        return None, None


def _prepare_3d_with_h(smiles: str, n_confs: int = N_CONFORMERS, seed: int = 42) -> Any:
    if Chem is None or AllChem is None:
        raise RuntimeError("RDKit unavailable")
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError("invalid smiles")
    return _prepare_3d_from_mol(mol, n_confs=n_confs, seed=seed)


def _prepare_3d_from_mol(mol: Any, n_confs: int = N_CONFORMERS, seed: int = 42) -> Any:
    if Chem is None or AllChem is None:
        raise RuntimeError("RDKit unavailable")
    mol_h = Chem.AddHs(Chem.Mol(mol))
    if mol_h.GetNumAtoms() > XTB_MAX_ATOMS:
        raise RuntimeError(f"molecule too large for xTB layer3 ({mol_h.GetNumAtoms()} atoms)")

    params = AllChem.ETKDGv3()
    params.randomSeed = seed
    params.numThreads = 1
    conf_ids = list(AllChem.EmbedMultipleConfs(mol_h, numConfs=max(1, int(n_confs)), params=params))
    if not conf_ids:
        status = AllChem.EmbedMolecule(mol_h, randomSeed=seed)
        if int(status) != 0:
            raise RuntimeError("RDKit embedding failed")
        conf_ids = [0]
    try:
        AllChem.MMFFOptimizeMoleculeConfs(mol_h, maxIters=500)
    except Exception:
        try:
            AllChem.MMFFOptimizeMolecule(mol_h)
        except Exception:
            pass
    return mol_h


def _lowest_energy_parent_conformer(
    mol_h: Any,
    calc: XTBCalculator,
    charge: int,
) -> Tuple[Optional[int], Optional[float]]:
    best_id: Optional[int] = None
    best_e: Optional[float] = None
    for conf_id in range(mol_h.GetNumConformers()):
        xyz = _mol_to_xyz_string(mol_h, conf_id=conf_id)
        if xyz is None:
            continue
        try:
            e_sp = calc.energy_from_xyz(xyz, charge=charge, uhf=0, optimize=False)
        except Exception:
            continue
        if best_e is None or e_sp < best_e:
            best_e = float(e_sp)
            best_id = int(conf_id)
    return best_id, best_e


def _heuristic_strain_from_smiles(smiles: str, default: float = 1.5) -> float:
    if Chem is None:
        return float(default)
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return float(default)
    n_heavy = int(mol.GetNumHeavyAtoms())
    if n_heavy <= 6:
        return 1.5
    if n_heavy <= 12:
        return 2.0
    return min(6.0, 2.0 + 0.25 * float(n_heavy - 12))


def compute_substrate_bde_xtb(
    smiles: str,
    bond_atom_indices: Tuple[int, int],
    *,
    solvent: Optional[str] = "water",
    xtb_path: str = "xtb",
    n_cores: int = 1,
    timeout_s: int = 300,
) -> Dict[str, Any]:
    if not is_layer3_xtb_enabled():
        return {
            "status": "disabled",
            "source": "layer3_xtb_disabled",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": None,
            "calibration_version": CALIBRATION_VERSION,
        }
    if not xtb_available(xtb_path=xtb_path):
        return {
            "status": "xtb_unavailable",
            "source": "layer3_xtb_unavailable",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": None,
            "calibration_version": CALIBRATION_VERSION,
        }
    try:
        mol_h = _prepare_3d_with_h(smiles)
        return compute_substrate_bde_xtb_for_mol(
            mol_h,
            bond_atom_indices,
            solvent=solvent,
            xtb_path=xtb_path,
            n_cores=n_cores,
            timeout_s=timeout_s,
        )
    except Exception as exc:
        return {
            "status": "error",
            "source": "layer3_xtb_error",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": 15.0,
            "error": str(exc),
            "calibration_version": CALIBRATION_VERSION,
        }


def compute_substrate_bde_xtb_for_mol(
    mol: Any,
    bond_atom_indices: Tuple[int, int],
    *,
    solvent: Optional[str] = "water",
    xtb_path: str = "xtb",
    n_cores: int = 1,
    timeout_s: int = 300,
) -> Dict[str, Any]:
    if not is_layer3_xtb_enabled():
        return {
            "status": "disabled",
            "source": "layer3_xtb_disabled",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": None,
            "calibration_version": CALIBRATION_VERSION,
        }
    if not xtb_available(xtb_path=xtb_path):
        return {
            "status": "xtb_unavailable",
            "source": "layer3_xtb_unavailable",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": None,
            "calibration_version": CALIBRATION_VERSION,
        }
    if Chem is None or AllChem is None:
        return {
            "status": "rdkit_unavailable",
            "source": "layer3_xtb_rdkit_unavailable",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": None,
            "calibration_version": CALIBRATION_VERSION,
        }

    heavy_idx, h_idx = int(bond_atom_indices[0]), int(bond_atom_indices[1])
    try:
        mol_h = _prepare_3d_from_mol(mol)
    except Exception as exc:
        return {
            "status": "error",
            "source": "layer3_xtb_error",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": 15.0,
            "error": str(exc),
            "calibration_version": CALIBRATION_VERSION,
        }

    if heavy_idx < 0 or heavy_idx >= mol_h.GetNumAtoms() or h_idx < 0 or h_idx >= mol_h.GetNumAtoms():
        return {
            "status": "index_error",
            "source": "layer3_xtb_index_error",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": 15.0,
            "calibration_version": CALIBRATION_VERSION,
        }

    heavy_atom = mol_h.GetAtomWithIdx(heavy_idx)
    h_atom = mol_h.GetAtomWithIdx(h_idx)
    if h_atom.GetSymbol() != "H":
        return {
            "status": "invalid_h_index",
            "source": "layer3_xtb_index_error",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": 15.0,
            "calibration_version": CALIBRATION_VERSION,
        }
    if heavy_atom.GetSymbol() not in VALID_RADICAL_HEAVY_ATOMS:
        return {
            "status": "invalid_heavy_atom",
            "source": "layer3_xtb_index_error",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": 15.0,
            "calibration_version": CALIBRATION_VERSION,
        }

    total_charge = int(sum(int(atom.GetFormalCharge()) for atom in mol_h.GetAtoms()))
    calc = XTBCalculator(
        xtb_path=xtb_path,
        method="gfn2",
        solvent=solvent,
        n_cores=n_cores,
        timeout_s=timeout_s,
    )

    try:
        best_conf_id, _ = _lowest_energy_parent_conformer(mol_h, calc, total_charge)
        if best_conf_id is None:
            best_conf_id = 0

        parent_xyz = _mol_to_xyz_string(mol_h, conf_id=best_conf_id)
        if parent_xyz is None:
            raise RuntimeError("parent xyz generation failed")

        e_parent = calc.energy_from_xyz(parent_xyz, charge=total_charge, uhf=0, optimize=True)

        radical_mol, radical_heavy_idx = _build_radical_from_parent(
            mol_h,
            heavy_idx=heavy_idx,
            h_idx=h_idx,
        )
        radical_xyz = None
        if radical_mol is not None and radical_mol.GetNumConformers() > 0:
            use_conf = int(best_conf_id)
            if use_conf >= radical_mol.GetNumConformers():
                use_conf = 0
            radical_xyz = _mol_to_xyz_string(radical_mol, conf_id=use_conf)
        if radical_xyz is None:
            # Fallback to geometry-derived radical xyz from parent conformer.
            radical_xyz = _mol_to_xyz_string(mol_h, conf_id=best_conf_id, remove_atom_idx=h_idx)
        if radical_xyz is None:
            raise RuntimeError("radical xyz generation failed")

        radical_charge = total_charge
        if radical_mol is not None:
            radical_charge = int(sum(int(atom.GetFormalCharge()) for atom in radical_mol.GetAtoms()))
        radical_unpaired = 0
        if radical_mol is not None:
            radical_unpaired = int(
                sum(int(atom.GetNumRadicalElectrons()) for atom in radical_mol.GetAtoms())
            )

        e_radical_vertical = calc.energy_from_xyz(
            radical_xyz,
            charge=radical_charge,
            uhf=1,
            optimize=False,
        )
        e_radical_adiabatic = calc.energy_from_xyz(
            radical_xyz,
            charge=radical_charge,
            uhf=1,
            optimize=True,
        )

        bde_vertical = (float(e_radical_vertical) + float(H_ATOM_ENERGY_HARTREE) - float(e_parent)) * HARTREE_TO_KJ_MOL
        bde_adiabatic = (float(e_radical_adiabatic) + float(H_ATOM_ENERGY_HARTREE) - float(e_parent)) * HARTREE_TO_KJ_MOL
        relaxation = float(bde_vertical - bde_adiabatic)

        return {
            "status": "ok",
            "source": "layer3_xtb_gfn2",
            "bde_kj_mol": round(float(bde_vertical), 1),
            "bde_vertical_kj_mol": round(float(bde_vertical), 1),
            "bde_adiabatic_kj_mol": round(float(bde_adiabatic), 1),
            "relaxation_energy_kj_mol": round(float(relaxation), 1),
            "uncertainty_kj_mol": 8.0,
            "method": "GFN2-xTB ALPB(radical uhf=1, parent uhf=0; vertical+adiabatic)",
            "solvent": solvent,
            "bond_atom_indices": [heavy_idx, h_idx],
            "radical_uhf": 1,
            "parent_uhf": 0,
            "n_conformers_screened": int(mol_h.GetNumConformers()),
            "best_conformer_id": int(best_conf_id),
            "radical_heavy_atom_index": radical_heavy_idx,
            "radical_unpaired_electrons": radical_unpaired,
            "energies_eh": {
                "parent": round(float(e_parent), 8),
                "radical_vertical": round(float(e_radical_vertical), 8),
                "radical_adiabatic": round(float(e_radical_adiabatic), 8),
                "h_atom": round(float(H_ATOM_ENERGY_HARTREE), 8),
            },
            "calibration_version": CALIBRATION_VERSION,
        }
    except Exception as exc:
        return {
            "status": "error",
            "source": "layer3_xtb_error",
            "bde_kj_mol": None,
            "uncertainty_kj_mol": 15.0,
            "error": str(exc),
            "bond_atom_indices": [heavy_idx, h_idx],
            "calibration_version": CALIBRATION_VERSION,
        }


def _apply_bde_safeguard(
    *,
    lookup_bde_kj_mol: Optional[float],
    lookup_uncertainty_kj_mol: Optional[float],
    xtb_result: Dict[str, Any],
    threshold_kj_mol: float = BDE_SAFEGUARD_THRESHOLD_KJ_MOL,
) -> Dict[str, Any]:
    xtb_bde = xtb_result.get("bde_kj_mol")
    if lookup_bde_kj_mol is None:
        return {
            "bde_kj_mol": xtb_bde if isinstance(xtb_bde, (int, float)) else None,
            "source": "xtb_only",
            "uncertainty_kj_mol": xtb_result.get("uncertainty_kj_mol", 15.0),
            "lookup_bde_kj_mol": None,
            "xtb_bde_kj_mol": xtb_bde if isinstance(xtb_bde, (int, float)) else None,
            "xtb_status": xtb_result.get("status"),
            "xtb_error": xtb_result.get("error"),
            "safeguard_threshold_kj_mol": float(threshold_kj_mol),
        }

    if not isinstance(xtb_bde, (int, float)):
        return {
            "bde_kj_mol": float(lookup_bde_kj_mol),
            "source": "lookup_fallback",
            "uncertainty_kj_mol": float(lookup_uncertainty_kj_mol or 10.0),
            "lookup_bde_kj_mol": float(lookup_bde_kj_mol),
            "xtb_bde_kj_mol": None,
            "xtb_status": xtb_result.get("status"),
            "xtb_error": xtb_result.get("error"),
            "safeguard_threshold_kj_mol": float(threshold_kj_mol),
        }

    deviation = abs(float(xtb_bde) - float(lookup_bde_kj_mol))
    delta_xtb = float(xtb_bde) - float(lookup_bde_kj_mol)
    if deviation <= float(threshold_kj_mol):
        correction = 0.5 * delta_xtb
        corrected_bde = float(lookup_bde_kj_mol) + float(correction)
        return {
            "bde_kj_mol": round(float(corrected_bde), 3),
            "source": "xtb_validated",
            "uncertainty_kj_mol": 6.0,
            "lookup_bde_kj_mol": float(lookup_bde_kj_mol),
            "xtb_bde_kj_mol": float(xtb_bde),
            "delta_xtb_kj_mol": round(float(delta_xtb), 3),
            "correction_applied_kj_mol": round(float(correction), 3),
            "deviation_kj_mol": round(float(deviation), 2),
            "xtb_status": xtb_result.get("status"),
            "xtb_error": xtb_result.get("error"),
            "safeguard_threshold_kj_mol": float(threshold_kj_mol),
        }

    return {
        "bde_kj_mol": float(lookup_bde_kj_mol),
        "source": "lookup_safeguard",
        "uncertainty_kj_mol": float(lookup_uncertainty_kj_mol or 10.0),
        "lookup_bde_kj_mol": float(lookup_bde_kj_mol),
        "xtb_bde_kj_mol": float(xtb_bde),
        "delta_xtb_kj_mol": round(float(delta_xtb), 3),
        "deviation_kj_mol": round(float(deviation), 2),
        "xtb_status": xtb_result.get("status"),
        "xtb_error": xtb_result.get("error"),
        "warning": (
            f"xTB BDE deviates by {deviation:.1f} kJ/mol from Layer 1 lookup; "
            "using lookup safeguard."
        ),
        "safeguard_threshold_kj_mol": float(threshold_kj_mol),
    }


def _cache_key_for_bde(
    mol: Any,
    bond_atom_indices: Tuple[int, int],
    bond_class: str,
    solvent: Optional[str],
) -> str:
    smiles = ""
    if Chem is not None and mol is not None:
        try:
            smiles = Chem.MolToSmiles(Chem.RemoveHs(Chem.Mol(mol)))
        except Exception:
            smiles = ""
    payload = {
        "smiles": smiles,
        "bond_atom_indices": [int(bond_atom_indices[0]), int(bond_atom_indices[1])],
        "bond_class": str(bond_class or ""),
        "solvent": str(solvent or "water"),
        "n_conformers": int(N_CONFORMERS),
        "safeguard_threshold": float(BDE_SAFEGUARD_THRESHOLD_KJ_MOL),
        "version": CALIBRATION_VERSION,
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()[:24]


def compute_substrate_bde_with_safeguard_for_mol(
    mol: Any,
    bond_atom_indices: Tuple[int, int],
    bond_class: str,
    *,
    solvent: Optional[str] = "water",
    xtb_path: str = "xtb",
    n_cores: int = 1,
    timeout_s: int = 300,
    threshold_kj_mol: float = BDE_SAFEGUARD_THRESHOLD_KJ_MOL,
) -> Dict[str, Any]:
    rec = l1_bde_record(bond_class)
    lookup_bde = rec.get("bde_kj_mol")
    lookup_unc = rec.get("uncertainty_kj_mol", 10.0)
    if not isinstance(lookup_bde, (int, float)):
        lookup_bde = l1_bde_kj_mol(bond_class, default=410.0)

    cache_path = None
    if mol is not None:
        cache_key = _cache_key_for_bde(mol, bond_atom_indices, bond_class, solvent)
        cache_path = _CACHE_DIR / f"{cache_key}.json"
        if cache_path.exists():
            try:
                cached = json.loads(cache_path.read_text(encoding="utf-8"))
                if cached.get("calibration_version") == CALIBRATION_VERSION:
                    return cached
            except Exception:
                pass

    xtb_result = compute_substrate_bde_xtb_for_mol(
        mol,
        bond_atom_indices,
        solvent=solvent,
        xtb_path=xtb_path,
        n_cores=n_cores,
        timeout_s=timeout_s,
    )

    payload = _apply_bde_safeguard(
        lookup_bde_kj_mol=float(lookup_bde),
        lookup_uncertainty_kj_mol=float(lookup_unc) if isinstance(lookup_unc, (int, float)) else 10.0,
        xtb_result=xtb_result,
        threshold_kj_mol=float(threshold_kj_mol),
    )
    payload["bond_class"] = str(bond_class)
    payload["calibration_version"] = CALIBRATION_VERSION
    payload["xtb_bde_vertical_kj_mol"] = xtb_result.get("bde_vertical_kj_mol")
    payload["xtb_bde_adiabatic_kj_mol"] = xtb_result.get("bde_adiabatic_kj_mol")
    payload["xtb_relaxation_energy_kj_mol"] = xtb_result.get("relaxation_energy_kj_mol")

    if cache_path is not None:
        try:
            cache_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
        except Exception:
            pass

    return payload


def compute_substrate_strain(
    smiles: str,
    *,
    bound_conformation_xyz: Optional[str] = None,
    solvent: Optional[str] = "water",
    xtb_path: str = "xtb",
    n_cores: int = 1,
    timeout_s: int = 300,
    default_kj_mol: float = 1.5,
) -> Dict[str, Any]:
    if not isinstance(smiles, str) or not smiles.strip():
        return {
            "status": "missing_smiles",
            "source": "layer3_xtb_missing_input",
            "strain_kj_mol": float(default_kj_mol),
            "calibration_version": CALIBRATION_VERSION,
        }

    if not is_layer3_xtb_enabled() or not xtb_available(xtb_path=xtb_path):
        return {
            "status": "fallback",
            "source": "heuristic_fallback",
            "strain_kj_mol": round(float(_heuristic_strain_from_smiles(smiles, default_kj_mol)), 2),
            "calibration_version": CALIBRATION_VERSION,
        }

    if Chem is None or AllChem is None:
        return {
            "status": "fallback",
            "source": "heuristic_fallback",
            "strain_kj_mol": round(float(_heuristic_strain_from_smiles(smiles, default_kj_mol)), 2),
            "calibration_version": CALIBRATION_VERSION,
        }

    calc = XTBCalculator(
        xtb_path=xtb_path,
        method="gfn2",
        solvent=solvent,
        n_cores=n_cores,
        timeout_s=timeout_s,
    )

    free_xyz = None
    try:
        mol_h = _prepare_3d_with_h(smiles)
        free_xyz = _mol_to_xyz_string(mol_h, conf_id=0)
        if free_xyz is None:
            raise RuntimeError("free xyz generation failed")
        e_opt = calc.energy_from_xyz(free_xyz, charge=0, uhf=0, optimize=True)

        if bound_conformation_xyz and os.path.exists(bound_conformation_xyz):
            bound_text = Path(bound_conformation_xyz).read_text(encoding="utf-8")
            e_bound = calc.energy_from_xyz(bound_text, charge=0, uhf=0, optimize=False)
            strain_kj = max(0.0, (float(e_bound) - float(e_opt)) * HARTREE_TO_KJ_MOL)
            return {
                "status": "ok",
                "source": "layer3_xtb_gfn2",
                "strain_kj_mol": round(float(strain_kj), 2),
                "mode": "bound_vs_optimized",
                "calibration_version": CALIBRATION_VERSION,
            }

        return {
            "status": "fallback",
            "source": "heuristic_fallback",
            "strain_kj_mol": round(float(_heuristic_strain_from_smiles(smiles, default_kj_mol)), 2),
            "mode": "heuristic_no_bound_geometry",
            "calibration_version": CALIBRATION_VERSION,
        }
    except Exception as exc:
        return {
            "status": "fallback",
            "source": "heuristic_fallback",
            "strain_kj_mol": round(float(_heuristic_strain_from_smiles(smiles, default_kj_mol)), 2),
            "error": str(exc),
            "calibration_version": CALIBRATION_VERSION,
        }
